"""Initial tables

Revision ID: 0ade6ddf1f14
Revises: 
Create Date: 2025-12-11 20:10:40.317195

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0ade6ddf1f14'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('moderation_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_event_id', sa.String(), nullable=False),
    sa.Column('content_id', sa.String(), nullable=True),
    sa.Column('submitter_id', sa.String(), nullable=True),
    sa.Column('content_kind', sa.Enum('text', 'image', 'mixed', name='contentkind'), nullable=False),
    sa.Column('text_excerpt', sa.String(length=512), nullable=True),
    sa.Column('image_uri', sa.Text(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('composite_timeout_seconds', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'aggregating', 'completed', 'failed', name='requeststatus'), nullable=False),
    sa.Column('policy_version', sa.String(length=64), nullable=True),
    sa.Column('requested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_event_id', name='uq_moderation_requests_source_event')
    )
    op.create_table('moderation_decisions',
    sa.Column('request_id', sa.UUID(), nullable=False),
    sa.Column('final_verdict', sa.Enum('allow', 'block', 'review', 'error', name='verdict'), nullable=False),
    sa.Column('final_score', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('timed_out', sa.Boolean(), nullable=False),
    sa.Column('moderator_count', sa.Integer(), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('emitted_event_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['request_id'], ['moderation_requests.id'], ),
    sa.PrimaryKeyConstraint('request_id')
    )
    op.create_table('moderator_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.UUID(), nullable=False),
    sa.Column('moderator_id', sa.String(length=128), nullable=False),
    sa.Column('modality', sa.Enum('text', 'image', name='moderatormodality'), nullable=False),
    sa.Column('status', sa.Enum('pending', 'completed', 'timed_out', 'errored', name='moderatorstatus'), nullable=False),
    sa.Column('verdict', sa.Enum('allow', 'block', 'review', 'error', name='verdict'), nullable=True),
    sa.Column('score', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['request_id'], ['moderation_requests.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('request_id', 'moderator_id', name='uq_moderator_runs_request_moderator')
    )
    op.create_index('ix_moderator_runs_request_modality', 'moderator_runs', ['request_id', 'modality'], unique=False)
    op.create_table('outbox_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=128), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.Enum('pending', 'published', 'failed', name='outboxstatus'), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['request_id'], ['moderation_requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_outbox_status_created_at', 'outbox_events', ['status', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_outbox_status_created_at', table_name='outbox_events')
    op.drop_table('outbox_events')
    op.drop_index('ix_moderator_runs_request_modality', table_name='moderator_runs')
    op.drop_table('moderator_runs')
    op.drop_table('moderation_decisions')
    op.drop_table('moderation_requests')
    # ### end Alembic commands ###
